ktor:
  application:
    modules:
      - ru.clevertec.ApplicationKt.module
  deployment:
    port: 8080
database:
  url: jdbc:postgresql://localhost:5435/questionnaire-api
  user: admin
  password: pass
  driver: org.postgresql.Driver
  maxPoolSize: 10
liquibase:
  changelog: db/changelog/db.changelog-master.yaml


#  kafka:
#    schema.registry.url:
#      - "SCHEMA_REGISTRY_URL"
#    common:
#      bootstrap.servers:
#        - "BOOTSTRAP_SERVERS"
#      # Additional attributes
#    admin:
#    # Additional attributes
#    consumer:
#      group.id: "my-group-id"
#      # Additional attributes
#    producer:
#      client.id: "my-client-id"
#      # Additional attributes
#    topics:
#      - name: my-topic
#        partitions: 1
#        configs:
#          message.timestamp.type: CreateTime
#          # Additional attributes
