ktor:
  application:
    modules:
      - ru.clevertec.ApplicationKt.module
  deployment:
    port: 8080
database:
  url: jdbc:postgresql://localhost:5435/questionnaire-api
  user: admin
  password: pass
  driver: org.postgresql.Driver
  maxPoolSize: 10
liquibase:
  changelog: db/changelog/db.changelog-master.yaml

  kafka:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      clientId: book-service-producer
      acks: all
      retries: 3
    topics:
      bookEvents: "book-events"
      authorEvents: "author-events"
